version: "3.8"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  frontend:
    build:
      context: ./
      dockerfile: ./client/dockerfile
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build: ./server/
    ports:
      - 8080:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/travel_destination
      DB_NAME: travel_destination
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
